name: crypto_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  colorize_text_avatar: ^1.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  numeral: ^2.0.1
  syncfusion_flutter_charts: ^24.1.41
  timeago: ^3.6.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/crypto.png
